nav:
 - 'Overview': index.md
 - 'Consensus and Security': consensus-and-security
 - 'Assets': assets.md
 - 'Smart Contracts': smart-contracts.md
 - 'Bridging': bridging.md
 - 'People and Identity': people-and-identity.md
 - 'Collectives and DAOs': collectives-and-daos.md
