let params = AuraParams {
    ...
    para_client: client.clone(),
    para_backend: backend.clone(),
    ...
    code_hash_provider: move |block_hash| {
        client.code_at(block_hash).ok().map(|c| ValidationCode::from(c).hash())
    },
    ...
    authoring_duration: Duration::from_millis(2000),
    ...
};