nav:
 - 'Get Started': get-started.md
 - 'Install Polkadot SDK': install-polkadot-sdk.md
 - 'Launch a Simple Parachain': launch-a-parachain
 - 'Customize Your Runtime': customize-runtime
 - 'Testing': testing
 - 'Runtime Upgrades and Maintenance': runtime-maintenance
 - 'Interoperability': interoperability
 - 'Integrations': integrations
