[parachain]
id = 100
add_to_genesis = true
cumulus_based = true
genesis_wasm_path = "/path/to/wasm"
genesis_state_path = "/path/to/state"

[[parachain.collators]]
name = "alice"
image = "polkadot-parachain"
command = "polkadot-parachain"
...