nav:
  - 'Home': index.md
  - 'Smart Contracts': smart-contracts
  - 'Parachains': parachains
  - 'Chain Interactions': chain-interactions
  # 'Get Support': get-support
  - 'Nodes and Validators': nodes-and-validators
