nav:
  - 'Home': index.md
  - 'Smart Contracts': smart-contracts
  - 'Parachains': parachains
  - 'Chain Interactions': chain-interactions
  - 'Node Infrastructure': node-infrastructure
  - 'Technical Reference': reference
  - 'AI Resources': ai-resources.md
  - 'Get Support': get-support
