nav:
  - 'Home': index.md
  - 'Smart Contracts': smart-contracts
  - 'Rollups': rollups
  - 'Chain Interctions': chain-interactions
  # 'Get Supported': get-support
  - 'Technical Reference': reference