nav:
  - 'Home': index.md
  - 'Smart Contracts': smart-contracts
  - 'Parachains': parachains
  # - 'Chain Interactions': chain-interactions
  - 'Node Infrastructure': node-infrastructure
  - 'Get Support': get-support
  - 'Technical Reference': reference
