title: Asset Hub
nav:
  - index.md
  - 'Register a Local Asset': register-local-asset.md
  - 'Register a Foreign Asset': register-foreign-asset.md
  - 'Convert Assets': 'asset-conversion.md'
  - 'Batch Teleport Assets': batch-teleport-assets.md