title: Asset Hub
nav:
  - index.md
  - 'Register a Local Asset': register-local-asset.md
  - 'Register a Foreign Asset': register-foreign-asset.md
  - 'Convert Assets': 'asset-conversion.md'
  - 'Send a Transaction Paying the Fee With a Different Token': send-a-tx-paying-fee-different-token.md
