nav:
 - 'Overview': index.md
 - 'Name Mechanism': name-mechanism.md
 - 'Architecture': architecture.md
 - 'PopRules and Pricing': poprules-pricing.md
 - 'Name Transfers': transfer.md
 - 'Escrow and Deposits': escrow.md
 - 'CLI': cli.md
 - 'TestNet Contracts': testnet-contracts.md
