nav:
 - 'Publish Your App Bundle': publish-your-app-bundle.md
 - 'Register and Publish': register-and-publish.md
 - 'Open Your App': open-your-app.md
 - 'Submit for Discoverability': submit-for-discoverability.md
