nav:
 - 'Get Started': get-started.md
 - 'Deploy a Contract': deploy-a-contract.md
#  - 'Verify a Contract': verify-a-contract.md # TODO: Add this once the feature is available
 - 'Troubleshooting': troubleshooting-faq.md
