global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: INSERT_YOUR_EMAIL
        from: INSERT_YOUR_EMAIL
        smarthost: smtp.gmail.com:587
        auth_username: INSERT_YOUR_EMAIL
        auth_identity: INSERT_YOUR_EMAIL
        auth_password: INSERT_YOUR_APP_PASSWORD
        send_resolved: true
