nav:
- 'Accounts': accounts.md
- 'Gas Model': gas-model.md
- 'Contract Deployment': contract-deployment.md
- 'Blocks, Transactions, and Fees': blocks-transactions-fees.md
- 'EVM vs PolkaVM': evm-vs-polkavm.md
- 'Dual VM Stack': dual-vm-stack.md
- 'JSON-RPC APIs': json-rpc-apis.md
# - 'Migration Guide': migration.md