name: PR Docs Build

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-docs:
    uses: papermoonio/workflows/.github/workflows/core-pr-mkdocs-build.yml@main
    with:
      mkdocs_repo: papermoonio/polkadot-mkdocs
      docs_repo: polkadot-developers/polkadot-docs
      docs_checkout: polkadot-docs
