name: Deploy Docs
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy documentation from"
        required: true
        default: "master"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential
      - name: Install pip requirements
        run: |
          python -m pip install --upgrade pip setuptools 'cython<3.0.0' wheel
          python -m pip install -r requirements.txt
      - name: Deploy Docs
        run: mkdocs gh-deploy --force --clean --site-dir ./site
