name: Rust CI for Tutorial Steps

on: [push, pull_request]

jobs:
  build:
    runs-on: rust
    strategy:
      matrix:
        step: [step1, step2, step3] # Add as many steps as you have

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Overlay step files and build
      run: |
        echo AAAAA